### POST
POST http://localhost:3000/api/cards/
Content-Type: application/json

{
    "text": "This was a post request!",
    "author": "Jason Doe"
}

### GET ALL
GET http://localhost:3000/api/cards

### GET ONE
GET http://localhost:3000/api/cards/61543c3fa22ddadc24887a41

### PUT
PUT http://localhost:3000/api/cards/1
Content-Type: application/json

{
    "text": "This was a put request!",
    "author": "John Doe"
}

### PATCH
PATCH http://localhost:3000/api/cards/1
Content-Type: application/json

{
    "text": "This was a patch request!"
}

### DELETE
DELETE http://localhost:3000/api/cards/61543c3fa22ddadc24887a41