### POST
POST http://localhost:3000/api/cards/
Content-Type: application/json

{
    "text": "This was a post request!",
    "author": "Jason Doe"
}

### GET ALL
GET http://localhost:3000/api/cards

### GET ONE
GET http://localhost:3000/api/cards/:id

### PUT
PUT http://localhost:3000/api/cards/:id
Content-Type: application/json

{
    "text": "This was a put request!",
    "author": "Julie Doe"
}

### PATCH
PATCH http://localhost:3000/api/cards/:id
Content-Type: application/json

{
    "text": "This was a patch request!"
}

### DELETE
DELETE http://localhost:3000/api/cards/:id